# Generated by Django 4.0.6 on 2022-09-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='advert',
            field=models.CharField(default=1, max_length=5000, verbose_name='Amazon'),
            preserve_default=False,
        ),
    ]
