# Generated by Django 4.0.6 on 2022-09-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_advert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='advert',
            field=models.TextField(verbose_name='Amazon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manager',
            field=models.CharField(default='admin', max_length=50, verbose_name='Owner'),
        ),
    ]
