# Generated by Django 4.0.6 on 2022-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_advert_alter_product_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manager',
            field=models.CharField(default='', max_length=50, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='product_name'),
        ),
    ]
